<table border="0" cellspacing="0" cellpadding="6" width="100%">
 <tr>
  <td>
   <p align="center" class="cms_h2 red">Работа с сайтом:</p>
   <p align="justify" class="cuprum">Нашим клиентам Мы предлагаем следующие платные услуги по работе с сайтом:</p>
   <div class="cms_h3 red"><a href="http://www.websun-com.ru/hosting/" target="_blank" class="no-link" title="Обслуживание сайта Нашими сотрудниками">- Обслуживание</a></div>
   <div class="cms_h3 red"><a href="http://www.websun-com.ru/SEO/" target="_blank" class="no-link" title="Продвижение сайта в поисковых системах">- Продвижение</a></div>
   <div class="cms_h3 red"><a href="http://www.websun-com.ru/" target="_blank" class="no-link" title="Написание уникальных статей для сайта">- Написание статей</a></div>
   <div class="cms_h3 red"><a href="http://www.websun-com.ru/" target="_blank" class="no-link" title="Приобретение доменный имён">- Домены</a></div>
   <div class="cms_h3 red"><a href="http://www.websun-com.ru/" target="_blank" class="no-link" title="Хостинг для сайта">- Хостинг</a></div>
   <div class="cms_h3 red"><a href="http://www.websun-com.ru/" target="_blank" class="no-link" title="Создание и размещение тематических видеороликов">- Видеоролики</a></div>
   <p align="center" class="cms_h2 red">Интерактив:</p>
   <div class="cms_h3 red"><a href="http://www.websun-com.ru/contacts/" target="_blank" class="no-link" title="Оставить отзыв по работе с CMS">- Оставить отзыв</a></div>
   <div class="cms_h3 red"><a href="http://www.websun-com.ru/contacts/" target="_blank" class="no-link" title="Внести предложение по работе с CMS">- Внести предложение</a></div>
  </td>
 </tr>
</table>