################################################################################
@auto[]
^connect[$site:connectString]{
	$this[^orders_cms::create[]]
	^cms.SetCurrentModule[$this.className]
}
################################################################################
@module_info[]
^use[./module_info.p]
$result[^module_information[]]
################################################################################